bsub -n 4 -W 24:00 -R "rusage[mem=16384]" python task2.py --model_name baseline_cnn
bsub -n 4 -W 24:00 -R "rusage[mem=16384]" python task2.py --model_name baseline_cnn --normalize
bsub -n 4 -W 24:00 -R "rusage[mem=16384]" python task2.py --model_name baseline_cnn --normalize --horizontal_flip
bsub -n 4 -W 24:00 -R "rusage[mem=16384]" python task2.py --model_name baseline_cnn --normalize --vertical_flip
bsub -n 4 -W 24:00 -R "rusage[mem=16384]" python task2.py --model_name baseline_cnn --normalize --rotate
bsub -n 4 -W 24:00 -R "rusage[mem=16384]" python task2.py --model_name baseline_cnn --normalize --perspective
bsub -n 4 -W 24:00 -R "rusage[mem=16384]" python task2.py --model_name baseline_cnn --normalize --color_jitter
bsub -n 4 -W 24:00 -R "rusage[mem=16384]" python task2.py --model_name baseline_cnn --normalize --random_crop
bsub -n 4 -W 24:00 -R "rusage[mem=16384]" python task2.py --model_name baseline_cnn --normalize --horizontal_flip --vertical_flip --rotate --color_jitter --random_crop --perspective

bsub -n 4 -W 24:00 -R "rusage[mem=16384]" python task2.py --model_name resnet_cnn
bsub -n 4 -W 24:00 -R "rusage[mem=16384]" python task2.py --model_name resnet_cnn --normalize
bsub -n 4 -W 24:00 -R "rusage[mem=16384]" python task2.py --model_name resnet_cnn --normalize --horizontal_flip
bsub -n 4 -W 24:00 -R "rusage[mem=16384]" python task2.py --model_name resnet_cnn --normalize --vertical_flip
bsub -n 4 -W 24:00 -R "rusage[mem=16384]" python task2.py --model_name resnet_cnn --normalize --rotate
bsub -n 4 -W 24:00 -R "rusage[mem=16384]" python task2.py --model_name resnet_cnn --normalize --perspective
bsub -n 4 -W 24:00 -R "rusage[mem=16384]" python task2.py --model_name resnet_cnn --normalize --color_jitter
bsub -n 4 -W 24:00 -R "rusage[mem=16384]" python task2.py --model_name resnet_cnn --normalize --random_crop
bsub -n 4 -W 24:00 -R "rusage[mem=16384]" python task2.py --model_name resnet_cnn --normalize --horizontal_flip --vertical_flip --rotate --color_jitter --random_crop --perspective

bsub -n 4 -W 24:00 -R "rusage[mem=16384]" python task2.py --model_name resnext_cnn
bsub -n 4 -W 24:00 -R "rusage[mem=16384]" python task2.py --model_name resnext_cnn --normalize
bsub -n 4 -W 24:00 -R "rusage[mem=16384]" python task2.py --model_name resnext_cnn --normalize --horizontal_flip
bsub -n 4 -W 24:00 -R "rusage[mem=16384]" python task2.py --model_name resnext_cnn --normalize --vertical_flip
bsub -n 4 -W 24:00 -R "rusage[mem=16384]" python task2.py --model_name resnext_cnn --normalize --rotate
bsub -n 4 -W 24:00 -R "rusage[mem=16384]" python task2.py --model_name resnext_cnn --normalize --perspective
bsub -n 4 -W 24:00 -R "rusage[mem=16384]" python task2.py --model_name resnext_cnn --normalize --color_jitter
bsub -n 4 -W 24:00 -R "rusage[mem=16384]" python task2.py --model_name resnext_cnn --normalize --random_crop
bsub -n 4 -W 24:00 -R "rusage[mem=16384]" python task2.py --model_name resnext_cnn --normalize --horizontal_flip --vertical_flip --rotate --color_jitter --random_crop --perspective